title: "Josh"


#author
author:
  name: 'Josh'
  firstname: 'Joshua'
  lastname: 'Darling'
  email: 'joshuadarling15@gmail.com'

#blog page
index:
  home: 'Home'
  about: 'About'
  life: 'Life'
  videos: 'Videos'
  clothing: 'Clothing'
  reviews: 'Reviews'


paginate: 2
paginator_path: "/blog/page:num/"


# Gems
gems: [jekyll-paginate]
